Week10
mautoranzo/06-jobs-api pull request #2
Opened 2023-01-10 00:24 UTC by mautoranzo

2023-01-16 21:25 UTC, aschey requested changes

2023-01-16 21:25 UTC, aschey commented on controllers/auth.js
> +const { findOne } = require('../models/User')
Minor detail, but you can remove this line since you're using `User.findOne` and you've already imported `User` on line 1 so this import doesn't do anything.

2023-01-16 21:25 UTC, aschey commented on controllers/songs.js
> +const Song = require('../models/Song')
The week 9 and 10 assignments should be for the jobs API I believe. Did you mean to make separate pull requests for the jobs API and your final project?

2023-01-17 00:56 UTC, mautoranzo commented on controllers/songs.js
> +const Song = require('../models/Song')
Maybe I misunderstood but I though that was the instructions asked for this weeks. But please let me know if I should change this.

https://learn.codethedream.org/ctd-node-express-class-lesson-9-jobs-api-part-1-a/

![image](https://user-images.githubusercontent.com/96083852/212786969-99947ec4-a6ab-4710-a0c0-cce038a88d3a.png)

2023-01-19 01:07 UTC, aschey commented on controllers/songs.js
> +const Song = require('../models/Song')
Yes this assignment is supposed to be for the jobs API. But I see files like this one https://github.com/mautoranzo/06-jobs-api/pull/2/files#diff-3293dd2fe246eb67342f97218a0d0caae3d403b2d11514d4bb3e75f0640f2da1 in here that are not for the jobs API.

2023-01-19 01:09 UTC, aschey commented on controllers/songs.js
> +const Song = require('../models/Song')
Oh my bad, I didn't read the bit at the beginning of the assignment. I see what you're doing, you're good.

2023-01-19 01:12 UTC, aschey approved these changes

2023-01-19 17:55 UTC, merged